name: idea_usher_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  velocity_x: 3.5.1
  flutter_svg: 1.1.1+1
  intl: 0.17.0
  percent_indicator: 4.2.2
  google_fonts: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/svg/.
  uses-material-design: true

